version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:3.9.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
         /nakama/nakama --config /nakama/data/pjcone.yml
    restart: always
    links:
      - "postgres:db"
    depends_on:
      - postgres
    volumes:
      - ./data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "11000" # exim4 이메일 반응자
      - "25" # exim4 smtp
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
      - "11000:11000"
      - "25:25"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
