version: '3'
services:
  godot-server:
    container_name: godot-server
    image: ubuntu
    volumes:
      - ./data:/server/
    expose:
      - "12000"
    ports:
      - "12000:12000"
    command: /server/Godot-3.4.4-stable.64 --main-pack /server/single_act.pck
    # command: tail -F anything